## ==========lidar config==========
# Detect distance and angle range
range_min : 0.0
range_max : 50.0
angle_min : -180.0
angle_max : 180.0
height_min : -0.5
height_max : 0.0
# Robot itself
robot_x_max : 0.6
robot_x_min : -0.6
robot_y_max : 0.4
robot_y_min : -0.4
robot_z_max : 0
robot_z_min : -0.9
# Map metadata
robot_frame : "base_link"
map_resolution : 0.15
obs_size : 2
dilating_size : 2
map_size : 50

